<script setup lang="ts">import{ref}from'vue';import{useSimulator}from'../simulator/store';import{scenarios}from'../simulator/scenarios';import{perception,type PerceptionKind}from'../simulator/perception';import{downloadTrace}from'../simulator/diagnostics';const sim=useSimulator();const tab=ref('设备'),battery=ref(80),sn=ref(''),scenario=ref('inspectionSuccess'),digitalHumanCode=ref('');const modules=['设备','MQTT','任务','导航','巡检','感知','实时智能体','数字人','OTA','诊断'];function event(type:string,payload:any={}){sim.log(type,payload)}function runScenario(){sim.scenario.run(scenarios[scenario.value],sim.log)}function anomaly(k:PerceptionKind){event('perception.'+k,perception(k))}</script>
<template><main><header><div><b>Robot Device Simulator</b><small> H5 · REAL DEVICE PROTOCOL</small></div><span>● SIMULATOR</span></header><section class="summary"><div>设备 SN<br><input v-model="sn" placeholder="deviceSn"/></div><div>电量<br><input v-model.number="battery" type="number"/>%</div><div>导航<br><strong>{{sim.nav.state}}</strong></div><div>任务<br><strong>{{sim.mission.status}}</strong></div></section><nav><button v-for="m in modules" :class="{active:tab===m}" @click="tab=m">{{m}}</button></nav>
<section class="grid"><article><h3>{{tab}}</h3>
<div v-if="tab==='设备'"><button @click="event('device.login',{sn})">设备认证</button><button @click="event('heartbeat',{battery})">发送心跳</button><button @click="event('device.offline')">离线</button></div>
<div v-else-if="tab==='MQTT'"><button @click="event('mqtt.connect')">连接 MQTT</button><button @click="event('mqtt.disconnect')">断开</button><p>真实连接参数通过环境/登录页配置；只允许 command/ota subscribe 与 state/event publish。</p></div>
<div v-else-if="tab==='任务'"><button @click="sim.mission.progress()">RUNNING</button><button @click="sim.mission.finish(true)">SUCCEEDED</button><button @click="sim.mission.finish(false,'SIM_FAILED')">FAILED</button></div>
<div v-else-if="tab==='导航'"><button @click="sim.nav.navigate({x:2,y:1,yaw:0})">导航目标</button><button @click="sim.nav.arrive()">到达</button><button @click="sim.nav.fail('BLOCKED')">阻塞</button><button @click="sim.nav.fail('LOCALIZATION_LOST')">定位丢失</button><pre>{{sim.nav.pose}}</pre></div>
<div v-else-if="tab==='巡检'"><button @click="sim.inspection.load(['客厅','餐桌','沙发','床'])">载入家庭巡检</button><button @click="sim.inspection.next()">下一点</button><button @click="sim.inspection.fail()">当前点失败</button><pre>{{sim.inspection.points}}</pre></div>
<div v-else-if="tab==='感知'"><button @click="anomaly('PERSON_FOUND')">发现人员</button><button @click="anomaly('FACE_MATCH')">人脸匹配</button><button @click="anomaly('FALL')">摔倒</button><button @click="anomaly('FIRE')">火情</button><button @click="anomaly('FRIDGE_OPEN')">冰箱门</button><button @click="anomaly('WATER_RUNNING')">水龙头</button></div>
<div v-else-if="tab==='实时智能体'"><button @click="event('realtime.connect')">连接 WSS</button><button @click="event('input.speech_started')">开始说话</button><button @click="event('input.speech_stopped')">结束说话</button><button @click="event('barge-in')">打断</button></div>
<div v-else-if="tab==='数字人'"><input v-model="digitalHumanCode" placeholder="digitalHumanCode"/><button @click="event('digitalHuman.connect',{digitalHumanCode})">加载</button><div class="robot">🤖</div><p>IDLE / LISTENING / THINKING / SPEAKING / EXECUTING / ERROR</p></div>
<div v-else-if="tab==='OTA'"><button @click="sim.ota.start({packageId:'demo'})">开始</button><button @click="sim.ota.advance(50)">50%</button><button @click="sim.ota.install()">安装</button><button @click="sim.ota.success()">成功</button><button @click="sim.ota.fail()">失败</button><p>{{sim.ota.state}} {{sim.ota.progress}}%</p></div>
<div v-else><select v-model="scenario"><option v-for="(_,k) in scenarios" :value="k">{{k}}</option></select><button @click="runScenario">运行场景</button><button @click="sim.scenario.pause()">暂停</button><button @click="sim.scenario.resume()">继续</button><button @click="sim.scenario.cancel()">取消</button><button @click="downloadTrace(sim.trace)">导出 Trace</button><button @click="sim.reset()">全部重置</button></div>
</article><aside><h3>事件时间线</h3><div class="timeline"><div v-for="e in sim.trace.events" :key="e.id"><b>{{e.type}}</b><small>{{new Date(e.at).toLocaleTimeString()}} · {{e.transport}}</small><pre>{{e.payload}}</pre></div></div></aside></section></main></template>